function StartBlock = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  STARTBLOCK = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  STARTBLOCK = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  StartBlock = importfile("/media/cephfs/labs/jbodurka/Obada/Projects/Capsule/sub_files/Start_Block.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-May-2020 14:00:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ID", "Enhanced_Block", "Start"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "ID", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "ID", "EmptyFieldRule", "auto");

% Import the data
StartBlock = readtable(filename, opts);

end